### ISSUE TITLE
preprocess

### ISSUE THREAD

**Issue by zhangjuan233** [lightdock/bm5#1]
Hello,

I'd like to ask a question: When using the DFIRE scoring function for experiments, is it necessary to preprocess the receptors, ligands, and complexes in the benchmark dataset? If so, what are the specific preprocessing steps, and which tools can be used to achieve this?

Looking forward to your response. Thank you!
![fg1](https://github.com/lightdock/bm5/assets/129643154/df65bca3-1968-4a5b-bf36-ee27d16cf8f9)

**Comment by JorgeRoel** [comment]
Hi @zhangjuan233 Thanks for your prompt. As you can see in the execution.sh as well as in the setup.json the starting structures used are PDBid_r_u.pdb and PDBid_l_u.pdb. Please note that for not all the cases r and l stand for receptor and ligand respectively. In general, receptor is the largest molecule.
